# cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-storageclass-to-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manage-storageclasses
subjects:
  - kind: ServiceAccount
    name: mongo
    namespace: btdevops
