trigger:
  branches:
    include:
      - main

variables:
  - imageName: "ubuntu-latest"
  - FRONTEND_APP: "frontend"
  - BACKEND_APP: "backend"
  - ACR_URI: "514191340653.dkr.ecr.ap-southeast-2.amazonaws.com" # change
  - IMAGE_TAG: "$(Build.BuildNumber)"
  - GIT_REPO: "https://github.com/tuyentrantb/sd1121_msa"
  - REPO_NAME: "sd1121_msa"

# Pool build
pool:
  vmImage: $(imageName)

resources:
  repositories:
    - repository: sd1121_msa
      type: github
      name: tuyentrantb/sd1121_msa
      ref: main

stages:
  - stage: Docker Build Frontend
    jobs:
      - job: Build
        steps:
          - script: |
              sh "az acr get-credentials -g practical-devops | docker login --username AZ --password-stdin $(ACR_URI)"
              sh "docker build -t $(FRONTEND_APP):$(IMAGE_TAG) src/frontend/"
              sh "docker tag $(FRONTEND_APP):$(IMAGE_TAG) $(ACR_URI)/$(FRONTEND_APP):latest"
              sh "docker push $(ACR_URI)/$(FRONTEND_APP):latest"
  - stage: Docker Build Backend
    jobs:
      - job: Build
        steps:
          - script: |
              sh "az acr get-credentials -g practical-devops | docker login --username AZ --password-stdin $(ACR_URI)"
              sh "docker build -t $(BACKEND_APP):$(IMAGE_TAG) src/backend/"
              sh "docker tag $(BACKEND_APP):$(IMAGE_TAG) $(ACR_URI)/$(BACKEND_APP):latest"
              sh "docker push $(ACR_URI)/$(BACKEND_APP):latest"
  - stage: Deploy k8s
    jobs:
      - job: Deploy
        steps:
          - script: |
              sh "az aks get-credentials -g practical-devops -n sd1121-devops-aks"
              sh "kubectl apply -f k8s/az/mongodb.yaml"
              sh "kubectl apply -f k8s/az/backend.yaml"
              sh "kubectl apply -f k8s/az/frontend.yaml"
